moneypenny:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "rsp.lsst.ac.uk"

  orders:
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
          - mountPath: /homedirs
            name: homedirs
    volumes:
      - name: homedirs
        nfs:
          server: 192.168.0.20
          path: /jhome

pull-secret:
  enabled: true
  path: "secret/k8s_operator/roe/pull-secret"
