orders:
  commission:
    - name: initcommission
      image: lsstsqre/inituserhome
      securityContext:
        runAsUser: 0
        runAsNonRootUser: false
      volumeMounts:
        - mountPath: /data/rsp/home
          name: home
  volumes:
    - name: home
      hostPath:
        path: /data/rsp/home
        type: Directory
