cadc-tap:
  tag: "1.0.3"
  use_mock_qserv: False
  qserv_host: "qserv-master01:4040"

  host: "lsst-lsp-int.ncsa.illinois.edu"

  secrets:
    enabled: False

  vault_secrets:
    enabled: True
    path: 'secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/tap'

  ingress:
    authenticated_annotations:
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Uid, X-Auth-Request-Token
      nginx.ingress.kubernetes.io/auth-url: https://lsst-lsp-int.ncsa.illinois.edu/auth?capability=read:tap&reissue_token=true
      nginx.ingress.kubernetes.io/configuration-snippet: |
        error_page 403 = @Basic401; # Basic401 configured in jwt-authorizer ingress rule
        auth_request_set $auth_token $upstream_http_x_auth_request_token;
        proxy_set_header Authorization "Bearer $auth_token";

  resources:
    requests:
      cpu: 2.0
      memory: 2G
    limits:
      cpu: 8.0
      memory: 16G

  aux_resources:
    requests:
      cpu: 0.25
      memory: 1G
    limits:
      cpu: 2.0
      memory: 4G

  gcs_bucket: 'async-results.lsst.codes'
  gcs_bucket_url: 'http://async-results.lsst.codes'
