cadc-tap-postgres:
  tag: "1.0"
  host: "science-platform-dev.lsst.cloud"

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/science-platform-dev.lsst.cloud/tap'

  gcs_bucket: 'async-results.lsst.codes'
  gcs_bucket_url: 'http://async-results.lsst.codes'
