dependencies:
  - name: landing-page
    version: ">=0.1.0"
    repository: https://lsst-sqre.github.io/charts/
  - name: cadc-tap
    version: ">=0.1.0"
    repository: https://lsst-sqre.github.io/charts/
