environment: tucson-teststand

argo:
  enabled: true
cert_manager:
  enabled: true
gafaelfawr:
  enabled: true
landing_page:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: false
nginx_ingress:
  enabled: false
nublado:
  enabled: true
obstap:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: true
tap:
  enabled: false
