environment: base

argo:
  enabled: true
cert_issuer:
  enabled: true
cert_manager:
  enabled: false
gafaelfawr:
  enabled: true
landing_page:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: false
nginx_ingress:
  enabled: false
nublado:
  enabled: true
obstap:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
tap:
  enabled: false
