environment: tucson-teststand

argo:
  enabled: false
gafaelfawr:
  enabled: true
landing_page:
  enabled: true
nginx_ingress:
  enabled: false
nublado:
  enabled: true
obstap:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: true
tap:
  enabled: false
