environment: nublado

argo:
  enabled: true
gafaelfawr:
  enabled: true
landing_page:
  enabled: true
logging:
  enabled: false
nginx_ingress:
  enabled: true
nublado:
  enabled: true
obstap:
  enabled: true
  revision: tickets/DM-25201
portal:
  enabled: true
postgres:
  enabled: true
tap:
  enabled: true
  revision: tickets/DM-25201
