environment: int

argo:
  enabled: true
gafaelfawr:
  enabled: true
landing_page:
  enabled: true
logging:
  enabled: true
  revision: tickets/DM-24542
nublado:
  enabled: true
obstap:
  enabled: true
portal:
  enabled: true
postgres:
  enabled: true
tap:
  enabled: true
