environment: gke

argo:
  enabled: true
  revision: HEAD
gafaelfawr:
  enabled: true
  revision: HEAD
landing_page:
  enabled: true
  revision: HEAD
logging:
  enabled: true
  revision: HEAD
nginx_ingress:
  enabled: true
  revision: HEAD
nublado:
  enabled: true
  revision: HEAD
obstap:
  enabled: true
  revision: HEAD
portal:
  enabled: true
  revision: HEAD
postgres:
  enabled: true
  revision: HEAD
tap:
  enabled: true
  revision: HEAD
