environment: bleed

argo:
  enabled: true
gafaelfawr:
  enabled: true
landing_page:
  enabled: true
logging:
  enabled: false
nginx_ingress:
  enabled: true
  revision: tickets/DM-25185
nublado:
  enabled: true
obstap:
  enabled: true
portal:
  enabled: true
postgres:
  enabled: true
tap:
  enabled: true
