apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "times-square.fullname" . }}-secret
  labels:
    {{- include "times-square.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.globals.vaultSecretsPathPrefix }}/times-square"
  type: Opaque
