apiVersion: v1
kind: Namespace
metadata:
  name: lsst-lsp-int-auth
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tap
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: lsst-lsp-int-auth
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/auth
    repoURL: https://github.com/lsst-sqre/lsp-deploy.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-int.yaml
