apiVersion: v1
kind: Namespace
metadata:
  name: landing-page
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing-page
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: landing-page
    server: https://kubernetes.default.svc
  project: default
  source:
    path: landing-page
    repoURL: https://github.com/lsst-sqre/charts.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/lsst-sqre/lsp-deploy/master/lsst-lsp-int/landing-page.yaml
  syncPolicy:
    automated:
      prune: true
