apiVersion: v1
kind: Namespace
metadata:
  name: tap
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tap
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: lsst-lsp-int-dax
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cadc-tap
    repoURL: https://github.com/lsst-sqre/charts.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/lsst-sqre/lsp-deploy/tickets/DM-22180/lsst-lsp-int/cadc-tap.yaml
  syncPolicy:
    automated:
      prune: true
