apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafdrop
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: sasquatch
          key: kafdrop-password
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        type: allow
        host: "*"
        operation: All
