image:
  tag: "tickets-DM-34613"

# Use the CSI storage class so that we can use snapshots.
redis:
  persistence:
    storageClass: "standard-rwo"

config:
  databaseUrl: "postgresql://gafaelfawr@localhost/gafaelfawr"

  # Support OpenID Connect clients like Chronograf.
  oidcServer:
    enabled: true

  cilogon:
    clientId: "cilogon:/client_id/46f9ae932fd30e9fb1b246972a3c0720"
    enrollmentUrl: "https://registry-test.lsst.codes/registry/co_petitions/start/coef:6"
    test: true

  firestore:
    project: "rsp-firestore-dev-31c4"
    migrate:
      enabled: true
      nfs:
        server: "10.87.86.26"
        path: "/share1/home"

  # Allow access by GitHub team.
  groupMapping:
    "admin:provision":
      - "lsst-sqre-square"
    "exec:admin":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "exec:notebook":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "exec:portal":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "read:image":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "read:tap":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"

  initialAdmins:
    - "afausti"
    - "athornton"
    - "cbanek"
    - "frossie"
    - "jonathansick"
    - "rra"
    - "simonkrughoff"

  errorFooter: |
    To report problems or ask for help, please open an issue in the
    <a href="https://github.com/rubin-dp0/Support/issues">GitHub
    rubin-dp0/Support project</a>.

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
  serviceAccount: "gafaelfawr@science-platform-dev-7696.iam.gserviceaccount.com"
