gafaelfawr:
  host: summit-lsp.lsst.codes
  ingress:
    host: summit-lsp.lsst.codes
  vault_secrets_path: "secret/k8s_operator/summit-lsp.lsst.codes/gafaelfawr"

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  # Use GitHub authentication.
  github:
    client_id: 220d64cbf46f9d2b7873

  # Allow access by GitHub team.
  group_mapping:
    "exec:admin": ["lsst-sqre-square"]
    "exec:user": ["lsst-sqre-square"]
    "read:workspace": ["lsst-sqre-square"]
    "read:workspace/user": ["lsst-sqre-square"]
    "write:workspace/user": ["lsst-sqre-square"]
    "exec:portal": ["lsst-sqre-square"]
    "exec:notebook": ["lsst-sqre-square"]
    "read:tap": ["lsst-sqre-square"]
    "read:image": ["lsst-sqre-square"]
