replicaCount: 2

pull_secret: 'pull-secret'
ingress:
  host: data-dev.lsst.eu
vaultSecretsPath: "secret/k8s_operator/rsp-cc/gafaelfawr"

redis:
  persistence:
    enabled: false

config:
  host:  data-dev.lsst.eu
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres.svc.local/gafaelfawr"

# Do not specify ingress.host because we're using the wildcard virtual host.

# Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  github:
    clientId: ae314e45a6af43ea910a

# Allow access by GitHub team.
  # Allow access by GitHub team.
  groupMapping:
    "admin:provision":
      - "rubin-in2p3-admin"
    "exec:admin":
      - "rubin-in2p3-admin"
    "exec:notebook":
      - "rubin-in2p3-admin"
      - "rubin-in2p3-user"
    "exec:portal":
      - "rubin-in2p3-admin"
      - "rubin-in2p3-user"
    "read:tap":
      - "rubin-in2p3-admin"
      - "rubin-in2p3-user"

  initialAdmins:
    - "gabrimaine"

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-cc/pull-secret
