# Reset token storage on every Redis restart.
redis:
  persistence:
    enabled: false

config:
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  # Use CILogon authentication.
  cilogon:
    clientId: "cilogon:/client_id/51ea95a5fac24d5a6f33e658d7d77d2a"
    loginParams:
      skin: "LSST"

  # Use NCSA groups to determine token scopes.
  groupMapping:
    "admin:provision": ["lsst_int_lsp_admin"]
    "exec:admin": ["lsst_int_lsp_admin"]
    "exec:notebook": ["lsst_int_lspdev"]
    "exec:portal": ["lsst_int_lspdev"]
    "read:tap": ["lsst_int_lspdev"]

  initialAdmins:
    - "afausti"
    - "athornto"
    - "cbanek"
    - "frossie"
    - "jsick"
    - "krughoff"
    - "rra"
