gafaelfawr:
  pull_secret: 'pull-secret'
  host: lsst-lsp-int.ncsa.illinois.edu
  ingress:
    host: lsst-lsp-int.ncsa.illinois.edu
  vault_secrets_path: "secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/gafaelfawr"

  # Use an existing, manually-managed PVC for Redis.
  redis:
    persistence:
      volumeClaimName: "auth-int-volume-claim"

  # IP range used by the cluster, used to determine the true client IP for
  # logging.
  proxies:
    - "141.142.181.0/24"

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  # Use CILogon authentication.
  cilogon:
    client_id: "cilogon:/client_id/6ca7b54ac075b65bccb9c885f9ba4a75"
    redirect_url: "https://lsst-lsp-int.ncsa.illinois.edu/oauth2/callback"
    login_params:
      skin: "LSST"

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/pull-secret
