apiVersion: v2
name: sasquatch
version: 1.0.0
description: SQuaRE telemetry data service.
dependencies:
  - name: "strimzi-kafka"
    version: 1.0.0
  - name: strimzi-registry-operator
    version: 1.2.0
    repository: https://lsst-sqre.github.io/charts/
  - name: influxdb
    version: 4.11.0
    repository: https://helm.influxdata.com/
  - name: kafka-connect-manager
    version: 1.0.0
  - name: chronograf
    version: 1.2.5
    repository: https://helm.influxdata.com/
  - name: kapacitor
    version: 1.4.6
    repository: https://helm.influxdata.com/
  - name: telegraf
    version: 1.8.18
    repository: https://helm.influxdata.com/
