strimzi-kafka:
  kafka:
    storage:
      storageClassName: rook-ceph-block
    externalListener:
      tls:
        enabled: true
      bootstrap:
        loadBalancerIP: "139.229.160.152"
        host: sasquatch-summit-kafka-bootstrap.lsst.codes
      brokers:
        - loadBalancerIP: "139.229.160.154"
          host: sasquatch-summit-kafka-0.lsst.codes
        - loadBalancerIP: "139.229.160.153"
          host: sasquatch-summit-kafka-1.lsst.codes
        - loadBalancerIP: "139.229.160.155"
          host: sasquatch-summit-kafka-2.lsst.codes
  zookeeper:
    storage:
      storageClassName: rook-ceph-block

influxdb:
  persistence:
    storageClass: rook-ceph-block
    size: 5Ti
  ingress:
    enabled: true
    hostname: summit-lsp.lsst.codes

kafka-connect-manager:
  influxdbSink:
    influxdb-sink:
      enabled: true

kafdrop:
  ingress:
    enabled: true
    hostname: summit-lsp.lsst.codes

chronograf:
  persistence:
    storageClass: rook-ceph-block
  ingress:
    enabled: true
    hostname: summit-lsp.lsst.codes
  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://summit-lsp.lsst.codes/auth/openid/login
    GENERIC_TOKEN_URL: https://summit-lsp.lsst.codes/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://summit-lsp.lsst.codes/.well-known/jwks.json
    GENERIC_API_URL: https://summit-lsp.lsst.codes/auth/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://summit-lsp.lsst.codes
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/summit.json

kapacitor:
  persistence:
    storageClass: rook-ceph-block
