sasquatch:
  strimzi-kafka: {}

  influxdb:
    ingress:
      enabled: true
      tls: false
      hostname: minikube.lsst.codes
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      path: /influxdb(/|$)(.*)

  chronograf:
    ingress:
      enabled: true
      tls: false
      hostname: minikube.lsst.codes
      annotations:
        kubernetes.io/ingress.class: "nginx"
      path: /chronograf(/|$)

    env:
      HOST_PAGE_DISABLED: true
      BASE_PATH: /chronograf
      GENERIC_NAME: "CILogon"
      GENERIC_AUTH_URL: https://minikube.lsst.codes/auth/openid/login
      GENERIC_TOKEN_URL: https://minikube.lsst.codes/auth/openid/token
      USE_ID_TOKEN: 1
      JWKS_URL: https://minikube.lsst.codes/.well-known/jwks.json
      GENERIC_API_URL: https://minikube.lsst.codes/auth/userinfo
      GENERIC_SCOPES: openid
      PUBLIC_URL: https://minikube.lsst.codes
      CUSTOM_AUTO_REFRESH: "1s=1000"
      STATUS_FEED_URL: "https://lsst-sqre.github.io/argocd-efd/apps/chronograf/feeds/minikube.json"


  vaultSecretsPath: secret/k8s_operator/minikube.lsst.codes/sasquatch

pull-secret:
  enabled: true
  path: secret/k8s_operator/minikube.lsst.codes/pull-secret
