{{- if .Values.publish_url }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "sherlock.fullname" . }}-secret
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/sherlock"
  type: Opaque
{{- end }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
spec:
  path: "{{- .Values.global.vaultSecretsPath }}/pull-secret"
  type: kubernetes.io/dockerconfigjson
