telegraf:
  # -- Allow network access to JupyterHub pod.
  podLabels:
    hub.jupyter.org/network-access-hub: "true"
  env:
    # -- Token to communicate with Influx
    - name: INFLUX_TOKEN
      valueFrom:
        secretKeyRef:
          name: telegraf
          key: influx-token
  service:
    # -- Telegraf service.
    enabled: false
  config:
    global_tags:
      # -- Cluster name -- should be same as FQDN of RSP endpoint
      # @default -- None, must be set
      cluster: ""
    # -- Telegraf processor plugins.
    processors: {}
    # -- Telegraf input plugins.
    # Collect JupyterHub Prometheus metrics by default.
    # See https://jupyterhub.readthedocs.io/en/stable/reference/metrics.html
    inputs:
      - prometheus:
          urls:
            - https://${telegraf.config.global_tags.cluster}/nb/hub/metrics
          # See https://docs.influxdata.com/influxdb/v2.1/reference/prometheus-metrics/
          metric_version: 2
    # -- Telegraf default output destination.
    outputs:
      - influxdb_v2:
          urls:
            - "https://roundtable-monitoring.lsst.cloud"
          bucket: "telegraf"
          token: "$INFLUX_TOKEN"
          organization: "lizard"
          # Should be less silly, I guess.

# -- Path to the Vault secrets (`secret/k8s_operator/<hostname>/telegraf`)
# @default -- None, must be set
vaultSecretsPath: ""
