vo-cutouts:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "data-int.lsst.cloud"
  vaultSecretsPath: "secret/k8s_operator/data-int.lsst.cloud/vo-cutouts"

  # Enable the frontend NetworkPolicy.
  networkPolicy:
    enabled: true

  config:
    butlerRepository: "s3://butler-us-central1-panda-dev/dc2/butler-external.yaml"
    databaseUrl: "postgresql://vo-cutouts@localhost/vo-cutouts"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
    serviceAccount: "vo-cutouts@science-platform-dev-7696.iam.gserviceaccount.com"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data-int.lsst.cloud/pull-secret"
