apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    name: {{ template "postgres.fullname" . }}
