elasticsearch:
  image:
    repository: "amazon/opendistro-for-elasticsearch"
    tag: "1.1.0"
  master:
    persistence:
      enabled: false
  data:
    replicas: 2
    persistence:
      enabled: false
    heapSize: "2g"
    resources:
      limits:
        cpu: "2"
        memory: 3G
      requests:
        cpu: "1"
        memory: 3G
  client:
    replicas: 2
    heapSize: "1g"
    resources:
      limits:
        cpu: "2"
        memory: 2G
      requests:
        cpu: "1"
        memory: 1G
  cluster:
    config:
      opendistro_security.disabled: true

kibana:
  image:
    repository: "lsstdax/kibana-no-security"
    #repository: "amazon/opendistro-for-elasticsearch-kibana"
    tag: "1.1.0"

  files:
    kibana.yml:
      elasticsearch.hosts: http://logging-elasticsearch-client:9200
      server.basePath: /logs
      server.rewriteBasePath: true

  ingress:
    enabled: false

fluentd-elasticsearch:
  elasticsearch:
    host: logging-elasticsearch-client
