influxdb2:
  # -- InfluxDB2 admin user; uses admin-password/admin-token keys from
  # secret.
  adminUser:
    # Too silly?
    organization: "lizard"
    bucket: "telegraf"
    retention_policy: "30d"
    existingSecret: influxdb2
  # -- InfluxDB2 ingress configuration.
  ingress:
    # @default -- False
    enabled: false
    tls: true
    secretName: influxdb2-tls
    # InfluxDB2 can't run behind a routed path--it must be on the root.
    # @default -- None, must be set, must not be the same as RSP ingress.
    hostname: ""
    # Note that this requires a CNAME
    # from: _acme_challenge.<hostname>.<domain>
    # to: _acme_challenge.tls.<domain>
    # cf https://phalanx.lsst.io/ops/cert-issuer/bootstrapping.html
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: cert-issuer-letsencrypt-dns
    path: /
    pathType: Prefix

# -- Path to the Vault secrets (`secret/k8s_operator/<hostname>/influxdb2`)
# @default -- None, must be set
vaultSecretsPath: ""
