{{- if .Values.nublado.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: nublado
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nublado-users
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nublado
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/nublado-users
    repoURL: https://github.com/lsst-sqre/lsp-deploy.git
    targetRevision: {{ .Values.nublado.revision }}
{{- end -}}
