apiVersion: v1
kind: Namespace
metadata:
  name: firefly
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: firefly
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/portal
    repoURL: https://github.com/lsst-sqre/lsp-deploy.git
    targetRevision: tickets/DM-22518
  syncPolicy:
    automated:
      prune: true
