{{- if .Values.postgres -}}
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: postgres
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/postgres
    repoURL: https://github.com/lsst-sqre/lsp-deploy.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-nublado.yaml
{{- end -}}
