{{- if .Values.sqlproxy_butler_int.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: sqlproxy-butler-int
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sqlproxy-butler-int
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sqlproxy-butler-int
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/sqlproxy-gcp
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    helm:
      parameters:
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vault_path_prefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.environment }}.yaml"
{{- end -}}
