apiVersion: v1
kind: Namespace
metadata:
  name: tap
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tap
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tap
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cadc-tap
    repoURL: https://github.com/lsst-sqre/charts.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: 'slack_webhook_url'
        value: 'abc'
      - name: 'google_creds'
        value: 'def'
  syncPolicy:
    automated:
      prune: true
