apiVersion: v1
kind: Namespace
metadata:
  name: tap
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tap
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/tap
    repoURL: https://github.com/lsst-sqre/lsp-deploy.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-gke.yaml
