{{- if .Values.vault_secrets_operator.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault-secrets-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/vault-secrets-operator
    repoURL: https://github.com/lsst-sqre/lsp-deploy.git
    targetRevision: {{ .Values.vault_secrets_operator.revision }}
{{- end -}}
