elasticsearch:
  host: nordic-bunny-elasticsearch-client
env:
 RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: 0.9
tolerations:
 - key: "dedicated"
   operator: "Exists"
   effect: "NoSchedule"
extraVolumes:
  - name: qservlogs
    hostPath:
      path: /qserv/log
extraVolumeMounts:
  - name: qservlogs
    mountPath: /qserv/log
extraConfigMaps:
  qserv.conf: |-
    # Example line:
    # 2019-04-24 23:05:29 140240301914240 [Note] InnoDB: 5.7.21 started; log sequence number 28871386
    <source>
      @id mysqld
      @type tail
      format /(?<time>\S*\s+\S*) (?<thread_id>\S+) \[(?<level>\S*)\]\s+(?<message>.*)/
      time_format %Y-%m-%d %k:%M:%S
      path /qserv/log/mysqld.log
      pos_file /qserv/log/mysqld.log.pos
      tag "mysqld.#{ENV['K8S_NODE_NAME']}"
      read_from_head true
      emit_unmatched_lines true
    </source>

    # Example line:
    # 2019-04-24 22:22:42: (message) Initiating shutdown, requested from signal handler
    <source>
      @id mysql-proxy
      @type tail
      format /(?<time>\S+\s+\S+) \((?<level>\S*)\)\s+(?<message>.*)/
      time_format %Y-%m-%d %H:%M:%S
      path /qserv/log/mysql-proxy.log
      pos_file /qserv/log/mysql-proxy.log.pos
      tag "mysql-proxy.#{ENV['K8S_NODE_NAME']}"
      read_from_head true
      emit_unmatched_lines true
    </source>

    # Example line:
    # [2019-09-05T10:40:13.189-0700] {{LWP,4567}{QID,4518#0}} DEBUG wdb.QueryRunner (core/modules/wdb/QueryRunner.cc:338) - _sendbuf wait end
    # Curly braces include Mapped Diagnostic Context with key/value pairs in curly braces separated by commas.
    # MDC keys are defined by Qserv and here we handle this set of keys:
    #   - LWP: thread/light-weight process ID (number)
    #   - CZID: czar ID (number)
    #   - TID: temporary query ID (number)
    #   - QID: query and optional job ID (number or two numbers separated by hash)
    # Unreadable regexp below handles all these keys and values, all unknown keys are ignored (by "[^}]*" expression)
    <source>
      @id xrootd
      @type tail
      format /\[(?<time>\S+T\S+)\]\s+\{(\{(LWP,(?<thread_id>\d+)|CZID,(?<czar_id>\d*)|TID,(?<query_id_tmp>\d*)|QID,((?<job_id>(?<query_id>\d*)#\d*)|(?<query_id>\d*))|[^}]*)\})+\}\s+(?<level>\S+)\s+(?<logger>\S+)\s+\((?<src_file>\S+)\)\s+-\s+(?<message>.*)/
      time_format %Y-%m-%dT%H:%M:%S.%L
      path /qserv/log/xrootd.log
      pos_file /qserv/log/xrootd.log.pos
      tag "xrootd.#{ENV['K8S_NODE_NAME']}"
      read_from_head true
      emit_unmatched_lines true
    </source>

    # Example line:
    # [2019-09-05T10:40:13.156-0700] {{CZID,1}{LWP,4728}{QID,4518}} DEBUG qdisp.JobQuery (core/modules/qdisp/JobQuery.cc:57) - JobQuery desc=0x7eff7400c8c0
    # See comment above for MDC format.
    <source>
      @id mysql-proxy-lua
      @type tail
      format /\[(?<time>\S+T\S+)\]\s+\{(\{(LWP,(?<thread_id>\d+)|CZID,(?<czar_id>\d*)|TID,(?<query_id_tmp>\d*)|QID,((?<job_id>(?<query_id>\d*)#\d*)|(?<query_id>\d*))|[^}]*)\})+\}\s+(?<level>\S+)\s+(?<logger>\S+)\s+\((?<src_file>\S+)\)\s+-\s+(?<message>.*)/
      time_format %Y-%m-%dT%H:%M:%S.%L
      path /qserv/log/mysql-proxy-lua.log
      pos_file /qserv/log/mysql-proxy-lua.log.pos
      tag "mysql-proxy-lua.#{ENV['K8S_NODE_NAME']}"
      read_from_head true
      emit_unmatched_lines true
    </source>
