squareone:
  ingress:
    host: "data-int.lsst.cloud"
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer-letsencrypt-dns
    tls:
      - secretName: squareone-tls
        hosts:
          - "data-int.lsst.cloud"
  imagePullSecrets:
    - name: "pull-secret"
  config:
    siteName: "Rubin Science Platform @ data-int"
    # broadcastMarkdown: |
    #    Patch Thursday **today** 3pm-5pm Pacific / 22:00-00:00 UT [(*what is RSP Patch Thursday?)*](https://www.lsst.io)

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-int.lsst.cloud/pull-secret
