squareone:
  replicaCount: 3
  ingress:
    host: "data.lsst.cloud"
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer-letsencrypt-dns
    tls:
      - secretName: squareone-tls
        hosts:
          - "data.lsst.cloud"
  imagePullSecrets:
    - name: "pull-secret"
  config:
    siteName: "Rubin Science Platform"
#    broadcastMarkdown: >
#      Patch Thursday **today** 3pm-5pm Pacific / 22:00-00:00 UT
#      [(*what is RSP Patch Thursday?)*](https://community.lsst.org/t/what-is-rsp-patch-thursday/5647)

pull-secret:
  enabled: true
  path: secret/k8s_operator/data.lsst.cloud/pull-secret
