squareone:
  ingress:
    host: "base-lsp.lsst.codes"
  imagePullSecrets:
    - name: "pull-secret"
  config:
    siteName: "Rubin Science Platform @ Base"

pull-secret:
  enabled: true
  path: secret/k8s_operator/base-lsp.lsst.codes/pull-secret
