squareone:
  image:
    pullPolicy: Always
    tag: tickets-DM-30839
  ingress:
    host: "data-dev.lsst.cloud"
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer-letsencrypt-dns
    tls:
      - secretName: squareone-tls
        hosts:
          - "data-dev.lsst.cloud"
  imagePullSecrets:
    - name: "pull-secret"
  config:
    siteName: "Rubin Science Platform @ data-dev"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-dev.lsst.cloud/pull-secret
