apiVersion: v1
kind: Secret
metadata:
  name: elastic-configsecret
type: Opaque
stringData:
  config.yml: |-
    _meta:
      type: "config"
      config_version: 2

    config:
      dynamic:
        authc:
          jwt_auth_domain:
            description: "Authenticate via JWT"
            enabled: false
            http_enabled: false
            transport_enabled: false
            order: 0
            http_authenticator:
              type: jwt
              challenge: false
              config:
                signing_key: "{{ .Values.signing_certificate | b64enc }}"
                jwt_header: "x-auth-request-token"
                jwt_url_parameter: null
                roles_key: null
                subject_key: null
            authentication_backend:
              type: noop
          basic_internal_auth_domain:
            description: "Authenticate via HTTP Basic against internal users database"
            http_enabled: true
            transport_enabled: true
            order: 4
            http_authenticator:
              type: basic
              challenge: true
            authentication_backend:
              type: intern
