apiVersion: v1
kind: Secret
metadata:
  name: kibana-configsecret
type: Opaque
stringData:
  config.yaml: |-
    _meta:
      type: "config"
      config_version: 2

    config:
      dynamic:
        authc:
          jwt_auth_domain:
            description: "Authenticate via JWT"
            http_enabled: true
            transport_enabled: true
            order: 0
            http_authenticator:
              type: jwt
              challenge: false
              config:
                signing_key: {{ .Values.signing_certificate | b64enc }}
                jwt_header: "x-auth-request-token"
                jwt_url_parameter: null
                roles_key: null
                subject_key: null
            authentication_backend:
              type: noop
