narrativelog:
  imagePullSecrets:
    - name: pull-secret
  ingress:
    host: base-lsp.lsst.codes

  site_id: base

vault_path: secret/k8s_operator/base-lsp.lsst.codes/postgres

pull-secret:
  enabled: true
  path: secret/k8s_operator/base-lsp.lsst.codes/pull-secret
