narrativelog:
  imagePullSecrets:
    - name: pull-secret
  ingress:
    enabled: true
    host: tucson-teststand.lsst.codes

  site_id: tucson

vault_path: secret/k8s_operator/tucson-teststand.lsst.codes/postgres

pull-secret:
  enabled: true
  path: secret/k8s_operator/tucson-teststand.lsst.codes/pull-secret
