solver:
  route53:
    aws_access_key_id: AKIAQSJOS2SFLUEVXZDB
    hosted_zone: Z06873202D7WVTZUFOQ42
    vault_secret_path: "secret/k8s_operator/tucson-teststand.lsst.codes/cert-manager"
fqdn: tucson-teststand.lsst.codes
cert-manager:
  installCRDs: true
