semaphore:
  ingress:
    enabled: true
    hosts:
      - host: "red-five.lsst.codes"
        paths:
          - path: "/semaphore"
            pathType: Prefix
  imagePullSecrets:
    - name: "pull-secret"

pull-secret:
  enabled: true
  path: secret/k8s_operator/red-five.lsst.codes/pull-secret
