semaphore:
  ingress:
    enabled: true
    hosts:
      - host: "data.lsst.cloud"
        paths:
          - path: "/semaphore"
  imagePullSecrets:
    - name: "pull-secret"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data.lsst.cloud/pull-secret
