semaphore:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: "minikube.lsst.codes"
        paths:
          - path: "/semaphore"
            pathType: Prefix
  imagePullSecrets:
    - name: "pull-secret"

pull-secret:
  enabled: true
  path: secret/k8s_operator/minikube.lsst.codes/pull-secret
