semaphore:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: "data-dev.lsst.cloud"
        paths:
          - path: "/semaphore"
            pathType: Prefix
  imagePullSecrets:
    - name: "pull-secret"
  vaultSecretsPath: "secret/k8s_operator/data-dev.lsst.cloud/semaphore"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-dev.lsst.cloud/pull-secret
