times-square:
  image:
    repository: ghcr.io/lsst-sqre/times-square
    tag: tickets-DM-33627
  ingress:
    host: "data-dev.lsst.cloud"
  vaultSecretsPath: "secret/k8s_operator/data-dev.lsst.cloud/times-square"
  config:
    environmentUrl: "https://data-dev.lsst.cloud"
    databaseUrl: "postgresql://times-square@localhost/times-square"
  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
    serviceAccount: "times-square@science-platform-dev-7696.iam.gserviceaccount.com"

times-square-ui:
  image:
    tag: tickets-dm-33930
  ingress:
    host: "data-dev.lsst.cloud"
