dependencies:
- name: vault-secrets-operator
  version: 1.10.1
  repository: https://ricoberger.github.io/helm-charts/
- name: pull-secret
  version: 0.1.2
  repository: https://lsst-sqre.github.io/charts/
