apiVersion: v1
kind: Namespace
metadata:
  name: gafaelfawr
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gafaelfawr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gafaelfawr
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/gafaelfawr
    repoURL: https://github.com/lsst-sqre/lsp-deploy.git
    targetRevision: tickets/DM-24367
    helm:
      valueFiles:
        - values-bleed.yaml
