postgres:
  vault_secrets:
    path: 'secret/k8s_operator/summit-lsp.lsst.codes/postgres'
  debug: 'true'
  jupyterhub_db:
    user: 'jovyan'
    db: 'jupyterhub'
  postgres_storage_class: 'rook-ceph-block'
