postgres:
  vault_secrets:
    path: 'secret/k8s_operator/gold-leader.lsst.codes/postgres'
  debug: 'true'
  jupyterhub_db:
    user: 'jovyan'
    db: 'jupyterhub'
  exposurelog_db:
    user: 'exposurelog'
    db: 'exposurelog'
  image:
    tag: '0.0.2'
