postgres:
  vault_secrets:
    path: 'secret/k8s_operator/minikube.lsst.codes/postgres'
  debug: 'true'
  jupyterhub_db:
    user: 'jovyan'
    db: 'jupyterhub'
  image:
    tag: '0.0.2'
  postgres_storage_class: 'standard'
