postgres:
  vault_secrets:
    path: 'secret/k8s_operator/base-lsp.lsst.codes/postgres'
  debug: 'true'
  jupyterhub_db:
    user: 'jovyan'
    db: 'jupyterhub'
  lovelog_db:
    user: 'lovelog'
    db: 'lovelog'
  postgres_storage_class: 'rook-ceph-block'
