postgres:
  vault_secrets:
    path: 'secret/k8s_operator/bleed.lsst.codes/postgres'
  debug: 'true'
  jupyterhub_db:
    user: 'jovyan'
    db: 'jupyterhub'
  exposurelog_db:
    user: 'exposurelog'
    db: 'exposurelog'
