debug: 'true'
jupyterhub_db:
  user: 'jovyan'
  db: 'jupyterhub'
exposurelog_db:
  user: 'exposurelog'
  db: 'exposurelog'
gafaelfawr_db:
  user: 'gafaelfawr'
  db: 'gafaelfawr'
narrativelog_db:
  user: 'narrativelog'
  db: 'narrativelog'
postgres_storage_class: 'standard'
