mobu:
  imagePullSecrets:
    - name: "pull-secret"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://lsst-lsp-stable.ncsa.illinois.edu/auth?scope=exec:admin"
    host: "lsst-lsp-stable.ncsa.illinois.edu"

  environmentUrl: "https://lsst-lsp-stable.ncsa.illinois.edu"
  vaultSecretsPath: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/mobu"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/pull-secret"
