mobu:
  imagePullSecrets:
    - name: "pull-secret"

  ingress:
    host: "rsp.lsst.ac.uk"

  environmentUrl: "https://rsp.lsst.ac.uk"
  vaultSecretsPath: "secret/k8s_operator/roe/mobu"

  autostart:
    - name: "python"
      count: 1
      users:
        - username: "systemtest01"
          uidnumber: 74768
      scopes: ["exec:notebook"]
      business: "JupyterPythonLoop"
      options:
        jupyter_options_form:
          image: "registry.hub.docker.com/lsstsqre/sciplat-lab:recommended"
          image_list: "registry.hub.docker.com/lsstsqre/sciplat-lab:recommended|Recommended|"
          image_dropdown: "use_image_from_dropdown"
          size: "Small"
      restart: True

pull-secret:
  enabled: true
  path: "secret/k8s_operator/roe/pull-secret"
