cachemachineImagePolicy: "desired"

autostart:
  - name: "firefighter"
    count: 1
    users:
      - username: "bot-mobu-recommended"
        uidnumber: 74768
    scopes:
      - "exec:notebook"
      - "exec:portal"
      - "read:image"
      - "read:tap"
    business: "NotebookRunner"
    options:
      repo_url: "https://github.com/SimonKrughoff/system-test.git"
      repo_branch: "prod"
      max_executions: 1
    restart: true
  - name: "weekly"
    count: 1
    users:
      - username: "bot-mobu-weekly"
        uidnumber: 74769
    scopes:
      - "exec:notebook"
      - "exec:portal"
      - "read:image"
      - "read:tap"
    business: "NotebookRunner"
    options:
      jupyter:
        image_class: "latest-weekly"
      repo_url: "https://github.com/lsst-sqre/system-test.git"
      repo_branch: "prod"
    restart: true
  - name: "sync-tap"
    count: 20
    user_spec:
      username_prefix: "sync-mobu-tap"
      uid_start: 74770
    scopes: ["read:tap"]
    business: "TAPQueryRunner"
    restart: true
    options:
      tap_sync: true
      tap_query_set: "dp0.2"
  - name: "async-tap-medium"
    count: 50
    user_spec:
      username_prefix: "async-mobu-tap"
      uid_start: 74800
    scopes: ["read:tap"]
    business: "TAPQueryRunner"
    restart: true
    options:
      tap_sync: false
      tap_query_set: "dp0.2-med-scans"
  - name: "async-tap-long"
    count: 50
    user_spec:
      username_prefix: "async-mobu-tap"
      uid_start: 75000
    scopes: ["read:tap"]
    business: "TAPQueryRunner"
    restart: true
    options:
      tap_sync: false
      tap_query_set: "dp0.2-long-scans"
