cachemachineImagePolicy: "desired"

autostart:
  - name: "firefighter"
    count: 1
    users:
      - username: "systemtest01"
        uidnumber: 74768
    scopes: ["exec:notebook", "exec:portal", "read:image", "read:tap"]
    business: "NotebookRunner"
    options:
      repo_url: "https://github.com/SimonKrughoff/system-test.git"
      repo_branch: "prod"
      max_executions: 1
    restart: true
  - name: "weekly"
    count: 1
    users:
      - username: "systemtest02"
        uidnumber: 74769
    scopes: ["exec:notebook", "exec:portal", "read:image", "read:tap"]
    business: "NotebookRunner"
    options:
      jupyter:
        image_class: "latest-weekly"
      repo_url: "https://github.com/lsst-sqre/system-test.git"
      repo_branch: "prod"
    restart: true
  - name: "tap"
    count: 30
    users:
      - username: "systemtest01"
        uidnumber: 74768
      - username: "systemtest02"
        uidnumber: 74769
      - username: "systemtest03"
        uidnumber: 74770
      - username: "systemtest04"
        uidnumber: 74771
      - username: "systemtest05"
        uidnumber: 74772
      - username: "systemtest06"
        uidnumber: 74773
      - username: "systemtest07"
        uidnumber: 74774
      - username: "systemtest08"
        uidnumber: 74775
      - username: "systemtest09"
        uidnumber: 74776
      - username: "systemtest10"
        uidnumber: 74777
      - username: "systemtest11"
        uidnumber: 74778
      - username: "systemtest12"
        uidnumber: 74779
      - username: "systemtest13"
        uidnumber: 74780
      - username: "systemtest14"
        uidnumber: 74781
      - username: "systemtest15"
        uidnumber: 74782
      - username: "systemtest16"
        uidnumber: 74783
      - username: "systemtest17"
        uidnumber: 74784
      - username: "systemtest18"
        uidnumber: 74785
      - username: "systemtest19"
        uidnumber: 74786
      - username: "systemtest20"
        uidnumber: 74787
      - username: "systemtest21"
        uidnumber: 74788
      - username: "systemtest22"
        uidnumber: 74789
      - username: "systemtest23"
        uidnumber: 74790
      - username: "systemtest24"
        uidnumber: 74791
      - username: "systemtest25"
        uidnumber: 74792
      - username: "systemtest26"
        uidnumber: 74793
      - username: "systemtest27"
        uidnumber: 74794
      - username: "systemtest28"
        uidnumber: 74795
      - username: "systemtest29"
        uidnumber: 74796
      - username: "systemtest30"
        uidnumber: 74797
    scopes: ["read:tap"]
    business: "TAPQueryRunner"
    restart: true
