mobu:
  imagePullSecrets:
    - name: "pull-secret"

  ingress:
    host: "data.lsst.cloud"

  environmentUrl: "https://data.lsst.cloud"
  vaultSecretsPath: "secret/k8s_operator/data.lsst.cloud/mobu"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data.lsst.cloud/pull-secret"
