ingress:
  host: "data-dev.lsst.cloud"

cachemachineImagePolicy: "desired"
environmentUrl: "https://data-dev.lsst.cloud"
vaultSecretsPath: "secret/k8s_operator/data-dev.lsst.cloud"

autostart:
  - name: "python"
    count: 1
    users:
      - username: "systemtest01"
        uidnumber: 74768
    scopes: ["exec:notebook"]
    business: "JupyterPythonLoop"
    options:
      jupyter:
        image_size: "Small"
    restart: true
