nublado:
  fqdn: nublado.lsst.codes

  oauth_provider: 'github'

  hub:
    image: 'lsstsqre/sciplat-hub:latest'

  wf:
    no_verify_signature: 'true'
    no_verify_audience: 'true'

  lab:
    restrict_nodes: 'true'
    image:
      experimentals: 2
      dailies: 2
      cachefile: '/home/jovyan/repo-cache.json'

    resources:
      nodejs_max_mem: '6144'
      mb_per_cpu: 2048

  routes:
    soda: '/api/image/soda'
    external:
      instance: 'https://nublado.lsst.codes'

  dask:
    restrict_nodes: 'true'

  vault_secrets:
    enabled: True
    path: secret/k8s_operator/nublado.lsst.codes/nublado

  mountpoints: |
    [
      { "disabled": true,
        "mountpoint": "/example -- if it doesn't start with '/' we add it",
        "fileserver-host": "omit to use Hub settings",
        "fileserver-export": "defaults to '/exports<mountpoint>'",
        "mode": "rw or ro, defaults to 'ro'",
        "options": "mount options, e.g. 'local_lock=all'"
      },
      {
       "mountpoint": "/home",
        "mode": "rw",
        "fileserver-host": "10.128.0.49",
        "fileserver-export": "/exports/home"
      },
      {
        "mountpoint": "/datasets",
        "fileserver-host": "10.128.0.49",
        "fileserver-export": "/exports/datasets"
      },
      {
        "mountpoint": "/project",
        "mode": "rw",
        "fileserver-host": "10.128.0.49",
        "fileserver-export": "/exports/project"
      },
      {
        "mountpoint": "/scratch",
        "mode": "rw",
        "fileserver-host": "10.128.0.49",
        "fileserver-export": "/exports/scratch"
      }
    ]
