nublado:
  fqdn: lsst-lsp-stable.ncsa.illinois.edu

  oauth_provider: 'jwt'

  lab:
    restrict_nodes: 'true'

    resources:
      nodejs_max_mem: '6144'
      mb_per_cpu: 3072

    image:
      cachefile: "/home/jovyan/repo-cache.json"

  reaper:
    enabled: true
    user: 'sqreadmin'

  hub:
    persistent_home: false
    image: 'lsstsqre/sciplat-hub:0.23.2'

  wf:
    no_verify_audience: 'true'
    image: 'lsstsqre/wfdispatcher:0.2.2.3'

  routes:
    soda: '/api/image/soda'
    external:
      instance: 'https://lsst-lsp-stable.ncsa.illinois.edu'

  dask:
    restrict_nodes: 'true'

  vault_secrets:
    enabled: true
    path: secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/nublado

  proxy:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
        nginx.ingress.kubernetes.io/auth-signin: "https://lsst-lsp-stable.ncsa.illinois.edu/login"
        nginx.ingress.kubernetes.io/auth-url: "https://lsst-lsp-stable.ncsa.illinois.edu/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /nb;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";
      host: lsst-lsp-stable.ncsa.illinois.edu

  mountpoints: |
    [
      { "disabled": true,
        "mountpoint": "/example -- if it doesn't start with '/' we add it",
        "fileserver-host": "omit to use Hub settings",
        "fileserver-export": "defaults to '/exports<mountpoint>'",
        "mode": "rw or ro, defaults to 'ro'",
        "options": "mount options, e.g. 'local_lock=all'"
      },
      {
       "mountpoint": "/home",
        "mode": "rw",
        "fileserver-host": "lsst-nfs.ncsa.illinois.edu",
        "fileserver-export": "/user/staff/jhome"
      },
      {
        "mountpoint": "/datasets",
        "fileserver-host": "lsst-nfs.ncsa.illinois.edu",
        "fileserver-export": "/user/precursor_data/datasets"
      },
      {
        "mountpoint": "/project",
        "mode": "rw",
        "fileserver-host": "lsst-nfs.ncsa.illinois.edu",
        "fileserver-export": "/user/staff/project"
      },
      {
        "mountpoint": "/scratch",
        "mode": "rw",
        "fileserver-host": "lsst-nfs.ncsa.illinois.edu",
        "fileserver-export": "/user/staff/scratch"
      },
      {
        "mountpoint": "/lsstdata/offline/teststand",
        "mode": "ro",
        "fileserver-host": "lsst-nfs.ncsa.illinois.edu",
        "fileserver-export": "/offline/teststand"
      }
    ]

  resourcemap: |
    [
      { "group": "lsst_int_lspdev",
        "resources": {
            "size_index": 3,
            "mem_quota": 626688,
            "cpu_quota": 204
        }
      }
    ]
