nublado:
  fqdn: lsst-nts-k8s.ncsa.illinois.edu

  oauth_provider: 'jwt'

  lab:
    restrict_nodes: 'true'
    multus: 'true'
    dds_domain: 'ncsa'
    image:
      repo_name: 'sal-sciplat-lab'
      experimentals: 0
      dailies: 0
      weeklies: 3
      releases: 1
      cachefile: '/home/jovyan/repo-cache.json'

    resources:
      nodejs_max_mem: '6144'
      mb_per_cpu: 3072
      options_form_sizes: 'tiny,small,medium,large,huge,colossal'
      size_index: 2

  reaper:
    enabled: True
    user: 'sqreadmin'
    keep_experimentals: 0
    keep_dailies: 0
    keep_weeklies: 78

  hub:
    persistent_home: False
    image: 'lsstsqre/sciplat-hub:latest'

  wf:
    no_verify_audience: 'true'

  routes:
    soda: '/api/image/soda'
    external:
      firefly: 'https://lsst-demo.ncsa.illinois.edu/firefly'
      instance: 'https://lsst-nts-k8s.ncsa.illinois.edu'

  dask:
    restrict_nodes: 'true'

  vault_secrets:
    enabled: True
    path: secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu/nublado

  proxy:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-request-redirect: $request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
        nginx.ingress.kubernetes.io/auth-signin: "https://lsst-nts-k8s.ncsa.illinois.edu/login"
        nginx.ingress.kubernetes.io/auth-url: "https://lsst-nts-k8s.ncsa.illinois.edu/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /nb;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
      host: lsst-nts-k8s.ncsa.illinois.edu

  mountpoints: |
    [
      { "disabled": true,
        "mountpoint": "/example -- if it doesn't start with '/' we add it",
        "fileserver-host": "omit to use Hub settings",
        "fileserver-export": "defaults to '/exports<mountpoint>'",
        "mode": "rw or ro, defaults to 'ro'",
        "options": "mount options, e.g. 'local_lock=all'"
      },
      {
       "mountpoint": "/home",
        "mode": "rw",
        "fileserver-host": "lsst-l1-cl-arctl.ncsa.illinois.edu",
        "fileserver-export": "/jhome"
      },
      {
        "disabled": true,
        "mountpoint": "/datasets",
        "fileserver-host": "lsst-l1-cl-arctl.ncsa.illinois.edu",
        "fileserver-export": "/user/precursor_data/datasets"
      },
      {
        "mountpoint": "/project",
        "mode": "rw",
        "fileserver-host": "lsst-l1-cl-arctl.ncsa.illinois.edu",
        "fileserver-export": "/project"
      },
      {
        "mountpoint": "/scratch",
        "mode": "rw",
        "fileserver-host": "lsst-l1-cl-arctl.ncsa.illinois.edu",
        "fileserver-export": "/scratch"
      },
      {
        "mountpoint": "/lsstdata/",
        "mode": "ro",
        "fileserver-host": "lsst-l1-cl-arctl.ncsa.illinois.edu",
        "fileserver-export": "/lsstdata"
      }
    ]

  resourcemap: |
    [
        { "disabled": true,
          "user": "Username for user with custom resources",
          "group": "Groupname for group with custom resources",
          "resources": {
              "size_index": "integer representing which size container is default: 0 is smallest",
              "mem_quota": "integer, namespace quota size in MB",
              "cpu_quota": "integer, namespace quota CPU limit"
          }
        },
        { "group": "lsst_int_lspdev"
        }
    ]

  signing_certificate: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyvr9LVjVWjwZDmWwmtGC
    dN1xxcsBL4pxkArRs64uSbhiZomReN+aL5C5rimYi7HnrAZq+VfBzzAxBYXO58Op
    BVvzRbEHFxjjM26wENlBSrDR+hHvGkXO9T/FNiTJiLtbaCeKS+7ZnJBhfFH/ELwH
    GJgbOgfmwtAocR8bKAFTERqmprqMPMiFKLSm7a3SnqOvXAqDT6q7eFCd5Vt1eX4b
    wXdPCw3WKIKp4sc5J2yKptSS4dVCB+FHtGy5ED1vB1HozrB33z2Cpza68YrcqL33
    sOMj6Dn3RZHeDjl3hObUK8cCsAPYJJekFYwE383+ahr5i+IvzSDwM8Cx1YA/UJB2
    6QIDAQAB
    -----END PUBLIC KEY-----
