apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: cert-issuer-letsencrypt-dns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sqre-admin@lists.lsst.org
    privateKeySecretRef:
      name: cert-manager-letsencrypt
    solvers:
      - dns01:
          cnameStrategy: Follow
          route53:
            region: us-east-1
            accessKeyID: {{ .Values.solver.route53.aws_access_key_id }}
            hostedZoneID: {{ .Values.solver.route53.hosted_zone }}
            secretAccessKeySecretRef:
              name: cert-issuer-secret
              key: aws-secret-access-key
