apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: influxdb2
  namespace: influxdb2
spec:
  path: {{ .Values.vaultSecretsPath }}/influxdb2
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: {{ .Values.vaultSecretsPath }}/pull-secret
  type: kubernetes.io/dockerconfigjson
