alert-stream-broker:
  kafka:
    # Addresses based on the state as of 2021-12-02; these were assigned by
    # Google and now we're pinning them.
    externalListener:
      bootstrap:
        ip: 35.188.169.31
        host: alert-stream-int.lsst.cloud
      brokers:
        - ip: 35.239.64.164
          host: alert-stream-int-broker-0.lsst.cloud
        - ip: 34.122.165.155
          host: alert-stream-int-broker-1.lsst.cloud
        - ip: 35.238.120.127
          host: alert-stream-int-broker-2.lsst.cloud

alert-stream-schema-registry:
  hostname: "alert-schemas-int.lsst.cloud"

alert-stream-simulator:
  clusterPort: 9092 # internal TLS listener
