vaultSecretsPath: "squash-sandbox.lsst.codes"
telegraf-ds:
  override_config:
    toml: |+
      [ global_tags ]
        cluster = "squash-sandbox.lsst.codes"
      [ agent ]
        hostname = "telegraf-$HOSTIP"
      [[inputs.kubernetes]]
        url = "https://$HOSTIP:10250"
        bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify = true
        namepass = ["kubernetes_pod_container"]
        fieldpass = ["cpu_usage_nanocores", "memory_usage_bytes"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "cert_manager"
        [outputs.influxdb_v2.tagpass]
          namespace = ["cert-manager"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "gafaelfawr"
        [outputs.influxdb_v2.tagpass]
          namespace = ["gafaelfawr"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "ingress_nginx"
        [outputs.influxdb_v2.tagpass]
          namespace = ["ingress-nginx"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "postgres"
        [outputs.influxdb_v2.tagpass]
          namespace = ["postgres"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "squash_api"
        [outputs.influxdb_v2.tagpass]
          namespace = ["squash-api"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "vault_secrets_operator"
        [outputs.influxdb_v2.tagpass]
          namespace = ["vault-secrets-operator"]
