vaultSecretsPath: "rsp.lsst.ac.uk"
telegraf-ds:
  override_config:
    toml: |+
      [ global_tags ]
        cluster = "rsp.lsst.ac.uk"
      [ agent ]
        hostname = "telegraf-$HOSTIP"
      [[inputs.kubernetes]]
        url = "https://$HOSTIP:10250"
        bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify = true
        namepass = ["kubernetes_pod_container"]
        fieldpass = ["cpu_usage_nanocores", "memory_usage_bytes"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_cachemachine"
        [outputs.influxdb_v2.tagpass]
          namespace = ["cachemachine"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_cert_manager"
        [outputs.influxdb_v2.tagpass]
          namespace = ["cert-manager"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_gafaelfawr"
        [outputs.influxdb_v2.tagpass]
          namespace = ["gafaelfawr"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_ingress_nginx"
        [outputs.influxdb_v2.tagpass]
          namespace = ["ingress-nginx"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_mobu"
        [outputs.influxdb_v2.tagpass]
          namespace = ["mobu"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_moneypenny"
        [outputs.influxdb_v2.tagpass]
          namespace = ["moneypenny"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_nublado2"
        [outputs.influxdb_v2.tagpass]
          namespace = ["nublado2"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_portal"
        [outputs.influxdb_v2.tagpass]
          namespace = ["portal"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_postgres"
        [outputs.influxdb_v2.tagpass]
          namespace = ["postgres"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_squareone"
        [outputs.influxdb_v2.tagpass]
          namespace = ["squareone"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_tap"
        [outputs.influxdb_v2.tagpass]
          namespace = ["tap"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_tap_schema"
        [outputs.influxdb_v2.tagpass]
          namespace = ["tap-schema"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_vault_secrets_operator"
        [outputs.influxdb_v2.tagpass]
          namespace = ["vault-secrets-operator"]
