telegraf-ds:
  override_config:
    toml: |+
      [ global_tags ]
        cluster = "lsst-lsp-int.ncsa.illinois.edu"
      [ agent ]
        hostname = "telegraf-$HOSTIP"
      [[inputs.kubernetes]]
        url = "https://$HOSTIP:10250"
        bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify = true
        namepass = ["kubernetes_pod_container"]
        fieldpass = ["cpu_usage_nanocores", "memory_usage_bytes"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_cachemachine"
        [outputs.influxdb_v2.tagpass]
          namespace = ["cachemachine"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_datalinker"
        [outputs.influxdb_v2.tagpass]
          namespace = ["datalinker"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_gafaelfawr"
        [outputs.influxdb_v2.tagpass]
          namespace = ["gafaelfawr"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_mobu"
        [outputs.influxdb_v2.tagpass]
          namespace = ["mobu"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_moneypenny"
        [outputs.influxdb_v2.tagpass]
          namespace = ["moneypenny"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_nublado2"
        [outputs.influxdb_v2.tagpass]
          namespace = ["nublado2"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_obstap"
        [outputs.influxdb_v2.tagpass]
          namespace = ["obstap"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_portal"
        [outputs.influxdb_v2.tagpass]
          namespace = ["portal"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_postgres"
        [outputs.influxdb_v2.tagpass]
          namespace = ["postgres"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_sasquatch"
        [outputs.influxdb_v2.tagpass]
          namespace = ["sasquatch"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_sherlock"
        [outputs.influxdb_v2.tagpass]
          namespace = ["sherlock"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_squareone"
        [outputs.influxdb_v2.tagpass]
          namespace = ["squareone"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_strimzi"
        [outputs.influxdb_v2.tagpass]
          namespace = ["strimzi"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_tap"
        [outputs.influxdb_v2.tagpass]
          namespace = ["tap"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_tap_schema"
        [outputs.influxdb_v2.tagpass]
          namespace = ["tap-schema"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_telegraf"
        [outputs.influxdb_v2.tagpass]
          namespace = ["telegraf"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_telegraf_ds"
        [outputs.influxdb_v2.tagpass]
          namespace = ["telegraf-ds"]
      [[outputs.influxdb_v2]]
            urls = ["https://monitoring.lsst.codes"]
            token = "$INFLUX_TOKEN"
            organization = "square"
        bucket = "k8s_vault_secrets_operator"
        [outputs.influxdb_v2.tagpass]
          namespace = ["vault-secrets-operator"]
