exposurelog:

  hostpath_1: /lsstdata/offline/teststand

  butler_uri_1: /volume_1/NCSA_comcam

  ingress:
    enabled: true
    annotations: {}
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    hosts:
      - host: lsst-nts-k8s.ncsa.illinois.edu
        paths: ["/exposurelog"]
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

vault_path: "secret/k8s_operator/nts.lsst.codes/postgres"
