exposurelog:
  imagePullSecrets:
    - name: pull-secret
  ingress:
    enabled: true
    host: summit-lsp.lsst.codes

  site_id: summit
  nfs_path_1: /repo/LSSTComCam  # Mounted as /volume_1
  nfs_server_1: comcam-arctl01.cp.lsst.org
  butler_uri_1: /volume_1

  nfs_path_2: /repo/LATISS  # Mounted as /volume_2
  nfs_server_2: atarchiver.cp.lsst.org
  butler_uri_2: /volume_2

vault_path: secret/k8s_operator/summit-lsp.lsst.codes/postgres

pull-secret:
  enabled: true
  path: secret/k8s_operator/summit-lsp.lsst.codes/pull-secret
