cachemachine:
  host: "minikube.lsst.codes"

  image:
    tag: "1.0.3"

  ingress:
    enabled: true
    hosts:
      - host: minikube.lsst.codes
        paths: ["/cachemachine"]

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/minikube.lsst.codes/pull-secret"
