cachemachine:
  host: "data-dev.lsst.cloud"

  image:
    tag: "1.0.2"

  ingress:
    enabled: true
    hosts:
      - host: data-dev.lsst.cloud
        paths: ["/cachemachine"]

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/data-dev.lsst.cloud/pull-secret"
