portal:
  imagePullSecrets:
    - name: "pull-secret"

  ingress:
    host: "rsp.lsst.ac.uk"

  resources:
    limits:
      memory: "8Gi"

  vaultSecretsPath: "secret/k8s_operator/roe/portal"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/roe/pull-secret"
