portal:
  replicaCount: 2

  imagePullSecrets:
    - name: "pull-secret"

  config:
    volumes:
      workareaHostPath: "/sui/firefly/workarea"
      configHostPath: "/sui/firefly/config"

  ingress:
    host: "lsst-lsp-stable.ncsa.illinois.edu"

  vaultSecretsPath: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/portal"

  nodeSelector:
    environment: "portal-stable"

  tolerations:
    - effect: "NoSchedule"
      key: "dedicated"
      operator: "Equal"
      value: "portal"

  resources:
    limits:
      memory: "24Gi"

  securityContext:
    runAsUser: 101
    runAsGroup: 102

pull-secret:
  enabled: true
  path: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/pull-secret"
