replicaCount: 2

resources:
  limits:
    memory: "2Gi"

image:
  tag: "suit-2022.3"

config:
  volumes:
    workareaNfs:
      path: "/share1/home/firefly/shared-workarea"
      server: "10.87.86.26"
