firefly:
  image:
    repository: "ipac/firefly"
    tag: "release-2020.2.0"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-method: GET
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Uid, X-Auth-Request-Token
      nginx.ingress.kubernetes.io/auth-signin: "https://nublado.lsst.codes/login"
      nginx.ingress.kubernetes.io/auth-url: "https://nublado.lsst.codes/auth?scope=exec:portal"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /portal/app;

  max_jvm_size: "7G"

  resources:
    limits:
      memory: 8Gi

  secrets:
    enabled: true

  redis:
    resources:
      limits:
        memory: 20Mi
