replicaCount: 2

resources:
  limits:
    memory: "2Gi"

image:
  tag: "suit-2022.4"

config:
  hipsUrl: "https://irsa.ipac.caltech.edu/data/hips/CDS/DSS2/color/"
  volumes:
    workareaNfs:
      path: "/share1/home/firefly/shared-workarea"
      server: "10.87.86.26"
