replicaCount: 1

config:
  volumes:
    workareaNfs:
      path: "/share1/home/firefly/shared-workarea"
      server: "10.22.240.130"
image:
  tag: "suit-2022.3"

resources:
  limits:
    memory: "30Gi"
