apiVersion: v1
kind: Namespace
metadata:
  name: lsst-lsp-stable-nb
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nublado
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: lsst-lsp-stable-nb
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/nublado
    repoURL: https://github.com/lsst-sqre/lsp-deploy.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-stable.yaml
  syncPolicy:
    automated:
      prune: true
