nublado2:
  jupyterhub:
    debug:
      enabled: true

    singleuser:
      storage:
        type: none

    ingress:
      hosts: ["minikube.lsst.codes"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes/login"

  config:
    base_url: "https://minikube.lsst.codes"

  vault_secret_path: "secret/k8s_operator/minikube.lsst.codes/nublado2"
  gafaelfawr_secret_path: "secret/k8s_operator/minikube.lsst.codes/gafaelfawr"
