nublado2:
  jupyterhub:
    debug:
      enabled: true

    hub:
      image:
        name: lsstsqre/nublado2
        tag: "1.0.0"

    singleuser:
      storage:
        type: none

    ingress:
      hosts: ["data-dev.lsst.cloud"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://data-dev.lsst.cloud/login"

  config:
    base_url: "https://data-dev.lsst.cloud/"

  vault_secret_path: "secret/k8s_operator/data-dev.lsst.cloud/nublado2"
