nublado2:
  jupyterhub:
    debug:
      enabled: true

    hub:
      image:
        name: lsstsqre/nublado2
        tag: "master"

    singleuser:
      storage:
        type: none
        extraVolumes:
          - name: datasets
            nfs:
              path: /share1/datasets
              server: 10.87.86.26
          - name: home
            nfs:
              path: /share1/home
              server: 10.87.86.26
          - name: project
            nfs:
              path: /share1/project
              server: 10.87.86.26
          - name: scratch
            nfs:
              path: /share1/scratch
              server: 10.87.86.26
        extraVolumeMounts:
          - name: datasets
            mountPath: /datasets
          - name: home
            mountPath: /home
          - name: project
            mountPath: /project
          - name: scratch
            mountPath: /scratch

    ingress:
      hosts: ["data-int.lsst.cloud"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://data-int.lsst.cloud/login"

  config:
    base_url: "https://data-int.lsst.cloud"

  vault_secret_path: "secret/k8s_operator/data-int.lsst.cloud/nublado2"
