nublado2:
  jupyterhub:
    debug:
      enabled: true
    ingress:
      hosts: ["minikube.lsst.codes"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes/login"
  config:
    base_url: "https://minikube.lsst.codes"
    butler_secret_path: "secret/k8s_operator/minikube.lsst.codes/butler-secret"
    pull_secret_path: "secret/k8s_operator/minikube.lsst.codes/pull-secret"
    lab_environment:
      AUTO_REPO_URLS: "https://github.com/lsst-sqre/system-test"
      AUTO_REPO_BRANCH: "prod"
      AUTO_REPO_SPECS: "https://github.com/lsst-sqre/system-test@prod"
      PANDA_AUTH_VO: Rubin
      PANDA_URL_SSL: https://pandaserver-doma.cern.ch:25443/server/panda
      PANDA_URL: http://pandaserver-doma.cern.ch:25080/server/panda
      IDDS_CONFIG: /opt/lsst/software/jupyterlab/panda/idds.cfg.client.template
      PANDA_CONFIG_ROOT: ~/
    volumes:
      - name: home
        emptyDir: {}
    volume_mounts:
      - name: home
        mountPath: /home

  vault_secret_path: "secret/k8s_operator/minikube.lsst.codes/nublado2"
