nublado2:
  jupyterhub:
    debug:
      enabled: true

    singleuser:
      storage:
        type: none
        extraVolumes:
          - name: datasets
            nfs:
              path: /share1/datasets
              server: 10.22.240.130
          - name: home
            nfs:
              path: /share1/home
              server: 10.22.240.130
          - name: project
            nfs:
              path: /share1/project
              server: 10.22.240.130
          - name: scratch
            nfs:
              path: /share1/scratch
              server: 10.22.240.130
          - name: tmp
            emptyDir: {}
          - name: passwd
            configMap:
              defaultMode: 420
              name: passwd
          - name: group
            configMap:
              defaultMode: 420
              name: group
          - name: shadow
            configMap:
              defaultMode: 384
              name: shadow
          - name: gshadow
            configMap:
              defaultMode: 384
              name: gshadow
        extraVolumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
            subPath: passwd
          - name: group
            mountPath: /etc/group
            readOnly: true
            subPath: group
          - name: shadow
            mountPath: /etc/shadow
            readOnly: true
            subPath: shadow
          - name: gshadow
            mountPath: /etc/gshadow
            readOnly: true
            subPath: gshadow
          - name: datasets
            mountPath: /datasets
          - name: home
            mountPath: /home
          - name: project
            mountPath: /project
          - name: scratch
            mountPath: /scratch

    ingress:
      hosts: ["data-int.lsst.cloud"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://data-int.lsst.cloud/login"

  config:
    base_url: "https://data-int.lsst.cloud"

  vault_secret_path: "secret/k8s_operator/data-int.lsst.cloud/nublado2"
  gafaelfawr_secret_path: "secret/k8s_operator/data-int.lsst.cloud/gafaelfawr"
