jupyterhub:
  debug:
    enabled: true
  hub:
    resources:
      requests:
        cpu: "2"
        memory: 3Gi

  singleuser:
    storage:
      type: none


  ingress:
    hosts: ["data-dev.lsst.eu"]
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://data-dev.lsst.eu/login"

config:
  base_url: "https://data-dev.lsst.eu/"
  butler_secret_path: "secret/k8s_operator/rsp-cc/butler-secret"
  pull_secret_path: "secret/k8s_operator/rsp-cc/pull-secret"

  volumes:
    hostPath:
      - name: data
        hostPath:
          path: /data/rsp/nublado2
          type: Directory
      - name: home
        hostPath:
          path: /data/rsp/home
          type: Directory

  volume_mounts:
      - name: data
        mountPath: /data
      - name: home
        mountPath: /home

vault_secret_path: "secret/k8s_operator/rsp-cc/nublado2"
gafaelfawr_secrets_path: "secret/k8s_operator/rsp-cc/gafaelfaw"


pull-secret:
  enabled: true
  path: "secret/k8s_operator/data.lsst.cloud/pull-secret"
