apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "noteburst.fullname" . }}
  labels:
    {{- include "noteburst.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.globals.vaultSecretsPathPrefix }}/noteburst"
  type: Opaque
